# Generated by Django 3.2.8 on 2022-06-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='gpa',
            field=models.IntegerField(blank=True, default=0, verbose_name='GPA'),
        ),
    ]
