# Generated by Django 3.0 on 2022-05-10 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='Answer 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='Answer 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='Answer 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, default='', max_length=280, null=True, verbose_name='Answer 4'),
        ),
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendance', models.PositiveIntegerField()),
                ('cgpa', models.CharField(max_length=10, verbose_name='CGPA')),
                ('gpa', models.CharField(max_length=10, verbose_name='GPA')),
                ('review', models.TextField(blank=True, default='', null=True)),
                ('score', models.PositiveIntegerField()),
                ('student', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.registerform')),
            ],
        ),
    ]
