# Generated by Django 3.2.8 on 2022-06-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testappear',
            name='dat',
            field=models.DateField(auto_now_add=True),
        ),
    ]
