# Generated by Django 3.2.8 on 2022-06-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_testappear_dat'),
    ]

    operations = [
        migrations.AddField(
            model_name='testappear',
            name='isappear',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
