# Generated by Django 3.2.8 on 2022-06-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_registerform_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='review',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
