# Generated by Django 3.2.8 on 2023-02-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_studentmarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmarks',
            name='attempt',
            field=models.BooleanField(default=False),
        ),
    ]
