# Generated by Django 3.2.8 on 2022-06-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_registerform_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='cgpa',
            field=models.IntegerField(blank=True, default=0, verbose_name='CGPA'),
        ),
    ]
