# Generated by Django 3.0 on 2022-05-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20220510_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_title', models.CharField(max_length=10)),
                ('is_answer', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option4',
        ),
        migrations.DeleteModel(
            name='Answerkey',
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.question'),
        ),
    ]
