# Generated by Django 3.2.8 on 2022-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_testappear_isappear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testappear',
            name='isappear',
            field=models.BooleanField(default=False),
        ),
    ]
