# Generated by Django 3.2.8 on 2022-06-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_studentreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(max_length=1000),
        ),
    ]
