# Generated by Django 3.2.8 on 2022-10-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_registerform_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentreport',
            name='percentage',
            field=models.FloatField(max_length=100),
        ),
    ]
