# Generated by Django 3.2.8 on 2022-05-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_adminform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='quiz',
            new_name='quiz1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='student',
        ),
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.CharField(blank=True, default='', max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, default='', max_length=280, null=True),
        ),
    ]
