# Generated by Django 3.2.8 on 2022-05-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20220527_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, default='', max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, default='', max_length=280, null=True),
        ),
    ]
