# Generated by Django 3.2.8 on 2022-06-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20220527_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='is_answer',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
