# Generated by Django 3.2.8 on 2022-06-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_option_is_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
