# Generated by Django 3.2.8 on 2022-06-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_option_is_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='time',
        ),
        migrations.RemoveField(
            model_name='record',
            name='Attendance',
        ),
        migrations.RemoveField(
            model_name='record',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='record',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='record',
            name='review',
        ),
        migrations.RemoveField(
            model_name='record',
            name='score',
        ),
        migrations.AddField(
            model_name='registerform',
            name='Attendance',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registerform',
            name='cgpa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='CGPA'),
        ),
        migrations.AddField(
            model_name='registerform',
            name='gpa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='GPA'),
        ),
        migrations.AddField(
            model_name='registerform',
            name='review',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='registerform',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
