# Generated by Django 3.2.8 on 2022-06-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_alter_option_is_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='cgpa',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CGPA'),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='gpa',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='GPA'),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='review',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='registerform',
            name='score',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
